[package]
name = "ajayfaulCoin"
version = "0.0.0"

[addresses]
NamedAddr = "0xCAFE"

[dependencies]
MoveStdlib = { local = "/home/jay/StackUp_Move_Campaign/move/language/move-stdlib", addr_subst = { "std" = "0x1" } }
